wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
wav2vec:
  desc: null
  value: facebook/wav2vec2-base
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 100
ACCUM_GRAD:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707126310.865017
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
